# Generated by Django 4.0 on 2021-12-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaGry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='ProducentGry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaGry', models.CharField(max_length=250)),
                ('dataWydania', models.DateField()),
                ('opis', models.CharField(max_length=300)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gry', to='Gry.kategoriagry')),
                ('producent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gry', to='Gry.producentgry')),
            ],
            options={
                'ordering': ('nazwaGry',),
            },
        ),
    ]
