# Generated by Django 4.0 on 2021-12-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producentgry',
            options={'ordering': ('nazwa',)},
        ),
    ]
