# Generated by Django 4.0 on 2021-12-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0003_alter_gry_options_alter_kategoriagry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gry',
            name='kategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gry', to='Gry.kategoriagry'),
        ),
        migrations.AlterField(
            model_name='gry',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gry', to='Gry.producentgry'),
        ),
    ]
