# Generated by Django 4.0 on 2021-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0004_alter_gry_kategoria_alter_gry_producent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriagry',
            name='nazwa',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
