# Generated by Django 4.0 on 2021-12-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0006_gry_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gry',
            options={'ordering': ('id',), 'verbose_name': 'Gra', 'verbose_name_plural': 'Gry'},
        ),
        migrations.AlterModelOptions(
            name='kategoriagry',
            options={'ordering': ('id',), 'verbose_name': 'KategoriaGry', 'verbose_name_plural': 'KategorieGier'},
        ),
        migrations.AlterModelOptions(
            name='producentgry',
            options={'ordering': ('id',), 'verbose_name': 'ProducentGry', 'verbose_name_plural': 'ProducenciGier'},
        ),
    ]
